// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlayerPosition string

const (
	PlayerPositionGoalkeeper PlayerPosition = "goalkeeper"
	PlayerPositionDefender   PlayerPosition = "defender"
	PlayerPositionMidfielder PlayerPosition = "midfielder"
	PlayerPositionAttacker   PlayerPosition = "attacker"
)

func (e *PlayerPosition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayerPosition(s)
	case string:
		*e = PlayerPosition(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayerPosition: %T", src)
	}
	return nil
}

type NullPlayerPosition struct {
	PlayerPosition PlayerPosition `json:"player_position"`
	Valid          bool           `json:"valid"` // Valid is true if PlayerPosition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayerPosition) Scan(value interface{}) error {
	if value == nil {
		ns.PlayerPosition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayerPosition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayerPosition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayerPosition), nil
}

type Player struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	TeamID    pgtype.UUID        `db:"team_id" json:"team_id"`
	FirstName string             `db:"first_name" json:"first_name"`
	LastName  string             `db:"last_name" json:"last_name"`
	Country   string             `db:"country" json:"country"`
	Position  PlayerPosition     `db:"position" json:"position"`
	Age       int32              `db:"age" json:"age"`
	Value     int64              `db:"value" json:"value"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Team struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Name      string             `db:"name" json:"name"`
	Country   string             `db:"country" json:"country"`
	Budget    int64              `db:"budget" json:"budget"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TransferList struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	PlayerID    pgtype.UUID        `db:"player_id" json:"player_id"`
	AskingPrice int64              `db:"asking_price" json:"asking_price"`
	ListedAt    pgtype.Timestamptz `db:"listed_at" json:"listed_at"`
}

type User struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	Password  string             `db:"password" json:"password"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
