// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: players.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (team_id, first_name, last_name, country, position, age, value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, team_id, first_name, last_name, country, position, age, value, created_at, updated_at
`

type CreatePlayerParams struct {
	TeamID    pgtype.UUID    `db:"team_id" json:"team_id"`
	FirstName string         `db:"first_name" json:"first_name"`
	LastName  string         `db:"last_name" json:"last_name"`
	Country   string         `db:"country" json:"country"`
	Position  PlayerPosition `db:"position" json:"position"`
	Age       int32          `db:"age" json:"age"`
	Value     int64          `db:"value" json:"value"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.TeamID,
		arg.FirstName,
		arg.LastName,
		arg.Country,
		arg.Position,
		arg.Age,
		arg.Value,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.FirstName,
		&i.LastName,
		&i.Country,
		&i.Position,
		&i.Age,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, team_id, first_name, last_name, country, position, age, value, created_at, updated_at FROM players WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.FirstName,
		&i.LastName,
		&i.Country,
		&i.Position,
		&i.Age,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayersByTeamID = `-- name: GetPlayersByTeamID :many
SELECT id, team_id, first_name, last_name, country, position, age, value, created_at, updated_at FROM players WHERE team_id = $1 ORDER BY position, last_name
`

func (q *Queries) GetPlayersByTeamID(ctx context.Context, teamID pgtype.UUID) ([]Player, error) {
	rows, err := q.db.Query(ctx, getPlayersByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.FirstName,
			&i.LastName,
			&i.Country,
			&i.Position,
			&i.Age,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transferPlayer = `-- name: TransferPlayer :one
UPDATE players
SET team_id = $2, position = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, team_id, first_name, last_name, country, position, age, value, created_at, updated_at
`

type TransferPlayerParams struct {
	ID       pgtype.UUID    `db:"id" json:"id"`
	TeamID   pgtype.UUID    `db:"team_id" json:"team_id"`
	Position PlayerPosition `db:"position" json:"position"`
}

func (q *Queries) TransferPlayer(ctx context.Context, arg TransferPlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, transferPlayer, arg.ID, arg.TeamID, arg.Position)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.FirstName,
		&i.LastName,
		&i.Country,
		&i.Position,
		&i.Age,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE players
SET first_name = $2, last_name = $3, country = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, team_id, first_name, last_name, country, position, age, value, created_at, updated_at
`

type UpdatePlayerParams struct {
	ID        pgtype.UUID `db:"id" json:"id"`
	FirstName string      `db:"first_name" json:"first_name"`
	LastName  string      `db:"last_name" json:"last_name"`
	Country   string      `db:"country" json:"country"`
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, updatePlayer,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Country,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.FirstName,
		&i.LastName,
		&i.Country,
		&i.Position,
		&i.Age,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
