// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTransfers(ctx context.Context) (int64, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (TransferList, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTransfer(ctx context.Context, id pgtype.UUID) error
	GetPlayerByID(ctx context.Context, id pgtype.UUID) (Player, error)
	GetPlayersByTeamID(ctx context.Context, teamID pgtype.UUID) ([]Player, error)
	GetTeamByUserID(ctx context.Context, userID pgtype.UUID) (Team, error)
	GetTransferByID(ctx context.Context, id pgtype.UUID) (TransferList, error)
	GetTransferByPlayerID(ctx context.Context, playerID pgtype.UUID) (TransferList, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]ListTransfersRow, error)
	TransferPlayer(ctx context.Context, arg TransferPlayerParams) (Player, error)
	UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (Player, error)
	UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error)
	UpdateTeamBudget(ctx context.Context, arg UpdateTeamBudgetParams) (Team, error)
}

var _ Querier = (*Queries)(nil)
