// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (user_id, name, country)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, country, budget, created_at, updated_at
`

type CreateTeamParams struct {
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Name    string      `db:"name" json:"name"`
	Country string      `db:"country" json:"country"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.UserID, arg.Name, arg.Country)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Country,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamByUserID = `-- name: GetTeamByUserID :one
SELECT id, user_id, name, country, budget, created_at, updated_at FROM teams
WHERE user_id = $1
`

func (q *Queries) GetTeamByUserID(ctx context.Context, userID pgtype.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByUserID, userID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Country,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeam = `-- name: UpdateTeam :one
UPDATE teams
SET name = $2, country = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, country, budget, created_at, updated_at
`

type UpdateTeamParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	Name    string      `db:"name" json:"name"`
	Country string      `db:"country" json:"country"`
}

func (q *Queries) UpdateTeam(ctx context.Context, arg UpdateTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeam, arg.ID, arg.Name, arg.Country)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Country,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTeamBudget = `-- name: UpdateTeamBudget :one
UPDATE teams
SET budget = budget + $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, name, country, budget, created_at, updated_at
`

type UpdateTeamBudgetParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Budget int64       `db:"budget" json:"budget"`
}

func (q *Queries) UpdateTeamBudget(ctx context.Context, arg UpdateTeamBudgetParams) (Team, error) {
	row := q.db.QueryRow(ctx, updateTeamBudget, arg.ID, arg.Budget)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Country,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
