// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransfers = `-- name: CountTransfers :one
SELECT COUNT(*) FROM transfer_list
`

func (q *Queries) CountTransfers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransfers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfer_list (player_id, asking_price)
VALUES ($1, $2)
RETURNING id, player_id, asking_price, listed_at
`

type CreateTransferParams struct {
	PlayerID    pgtype.UUID `db:"player_id" json:"player_id"`
	AskingPrice int64       `db:"asking_price" json:"asking_price"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (TransferList, error) {
	row := q.db.QueryRow(ctx, createTransfer, arg.PlayerID, arg.AskingPrice)
	var i TransferList
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.AskingPrice,
		&i.ListedAt,
	)
	return i, err
}

const deleteTransfer = `-- name: DeleteTransfer :exec
DELETE FROM transfer_list WHERE id = $1
`

func (q *Queries) DeleteTransfer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransfer, id)
	return err
}

const getTransferByID = `-- name: GetTransferByID :one
SELECT id, player_id, asking_price, listed_at FROM transfer_list WHERE id = $1
`

func (q *Queries) GetTransferByID(ctx context.Context, id pgtype.UUID) (TransferList, error) {
	row := q.db.QueryRow(ctx, getTransferByID, id)
	var i TransferList
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.AskingPrice,
		&i.ListedAt,
	)
	return i, err
}

const getTransferByPlayerID = `-- name: GetTransferByPlayerID :one
SELECT id, player_id, asking_price, listed_at FROM transfer_list WHERE player_id = $1
`

func (q *Queries) GetTransferByPlayerID(ctx context.Context, playerID pgtype.UUID) (TransferList, error) {
	row := q.db.QueryRow(ctx, getTransferByPlayerID, playerID)
	var i TransferList
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.AskingPrice,
		&i.ListedAt,
	)
	return i, err
}

const listTransfers = `-- name: ListTransfers :many
SELECT
  tl.id,
  tl.player_id,
  tl.asking_price,
  tl.listed_at,
  p.first_name,
  p.last_name,
  p.position,
  p.value,
  t.name AS team_name
FROM transfer_list tl
JOIN players p ON p.id = tl.player_id
JOIN teams   t ON t.id = p.team_id
ORDER BY tl.listed_at DESC
LIMIT $1 OFFSET $2
`

type ListTransfersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListTransfersRow struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	PlayerID    pgtype.UUID        `db:"player_id" json:"player_id"`
	AskingPrice int64              `db:"asking_price" json:"asking_price"`
	ListedAt    pgtype.Timestamptz `db:"listed_at" json:"listed_at"`
	FirstName   string             `db:"first_name" json:"first_name"`
	LastName    string             `db:"last_name" json:"last_name"`
	Position    PlayerPosition     `db:"position" json:"position"`
	Value       int64              `db:"value" json:"value"`
	TeamName    string             `db:"team_name" json:"team_name"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]ListTransfersRow, error) {
	rows, err := q.db.Query(ctx, listTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransfersRow{}
	for rows.Next() {
		var i ListTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.AskingPrice,
			&i.ListedAt,
			&i.FirstName,
			&i.LastName,
			&i.Position,
			&i.Value,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
