// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/querier.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/querier.go -destination=internal/repository/mock/mock_querier.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	repository "github.com/faikbairamov/soccer-manager/internal/repository"
	pgtype "github.com/jackc/pgx/v5/pgtype"
	gomock "go.uber.org/mock/gomock"
)

// MockQuerier is a mock of Querier interface.
type MockQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder
	isgomock struct{}
}

// MockQuerierMockRecorder is the mock recorder for MockQuerier.
type MockQuerierMockRecorder struct {
	mock *MockQuerier
}

// NewMockQuerier creates a new mock instance.
func NewMockQuerier(ctrl *gomock.Controller) *MockQuerier {
	mock := &MockQuerier{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuerier) EXPECT() *MockQuerierMockRecorder {
	return m.recorder
}

// CountTransfers mocks base method.
func (m *MockQuerier) CountTransfers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountTransfers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountTransfers indicates an expected call of CountTransfers.
func (mr *MockQuerierMockRecorder) CountTransfers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountTransfers", reflect.TypeOf((*MockQuerier)(nil).CountTransfers), ctx)
}

// CreatePlayer mocks base method.
func (m *MockQuerier) CreatePlayer(ctx context.Context, arg repository.CreatePlayerParams) (repository.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePlayer", ctx, arg)
	ret0, _ := ret[0].(repository.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePlayer indicates an expected call of CreatePlayer.
func (mr *MockQuerierMockRecorder) CreatePlayer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePlayer", reflect.TypeOf((*MockQuerier)(nil).CreatePlayer), ctx, arg)
}

// CreateTeam mocks base method.
func (m *MockQuerier) CreateTeam(ctx context.Context, arg repository.CreateTeamParams) (repository.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, arg)
	ret0, _ := ret[0].(repository.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockQuerierMockRecorder) CreateTeam(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockQuerier)(nil).CreateTeam), ctx, arg)
}

// CreateTransfer mocks base method.
func (m *MockQuerier) CreateTransfer(ctx context.Context, arg repository.CreateTransferParams) (repository.TransferList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", ctx, arg)
	ret0, _ := ret[0].(repository.TransferList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockQuerierMockRecorder) CreateTransfer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockQuerier)(nil).CreateTransfer), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockQuerier) CreateUser(ctx context.Context, arg repository.CreateUserParams) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockQuerierMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockQuerier)(nil).CreateUser), ctx, arg)
}

// DeleteTransfer mocks base method.
func (m *MockQuerier) DeleteTransfer(ctx context.Context, id pgtype.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransfer", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransfer indicates an expected call of DeleteTransfer.
func (mr *MockQuerierMockRecorder) DeleteTransfer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransfer", reflect.TypeOf((*MockQuerier)(nil).DeleteTransfer), ctx, id)
}

// GetPlayerByID mocks base method.
func (m *MockQuerier) GetPlayerByID(ctx context.Context, id pgtype.UUID) (repository.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayerByID", ctx, id)
	ret0, _ := ret[0].(repository.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayerByID indicates an expected call of GetPlayerByID.
func (mr *MockQuerierMockRecorder) GetPlayerByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayerByID", reflect.TypeOf((*MockQuerier)(nil).GetPlayerByID), ctx, id)
}

// GetPlayersByTeamID mocks base method.
func (m *MockQuerier) GetPlayersByTeamID(ctx context.Context, teamID pgtype.UUID) ([]repository.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayersByTeamID", ctx, teamID)
	ret0, _ := ret[0].([]repository.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayersByTeamID indicates an expected call of GetPlayersByTeamID.
func (mr *MockQuerierMockRecorder) GetPlayersByTeamID(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayersByTeamID", reflect.TypeOf((*MockQuerier)(nil).GetPlayersByTeamID), ctx, teamID)
}

// GetTeamByUserID mocks base method.
func (m *MockQuerier) GetTeamByUserID(ctx context.Context, userID pgtype.UUID) (repository.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamByUserID", ctx, userID)
	ret0, _ := ret[0].(repository.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamByUserID indicates an expected call of GetTeamByUserID.
func (mr *MockQuerierMockRecorder) GetTeamByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamByUserID", reflect.TypeOf((*MockQuerier)(nil).GetTeamByUserID), ctx, userID)
}

// GetTransferByID mocks base method.
func (m *MockQuerier) GetTransferByID(ctx context.Context, id pgtype.UUID) (repository.TransferList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransferByID", ctx, id)
	ret0, _ := ret[0].(repository.TransferList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransferByID indicates an expected call of GetTransferByID.
func (mr *MockQuerierMockRecorder) GetTransferByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransferByID", reflect.TypeOf((*MockQuerier)(nil).GetTransferByID), ctx, id)
}

// GetTransferByPlayerID mocks base method.
func (m *MockQuerier) GetTransferByPlayerID(ctx context.Context, playerID pgtype.UUID) (repository.TransferList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransferByPlayerID", ctx, playerID)
	ret0, _ := ret[0].(repository.TransferList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransferByPlayerID indicates an expected call of GetTransferByPlayerID.
func (mr *MockQuerierMockRecorder) GetTransferByPlayerID(ctx, playerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransferByPlayerID", reflect.TypeOf((*MockQuerier)(nil).GetTransferByPlayerID), ctx, playerID)
}

// GetUserByEmail mocks base method.
func (m *MockQuerier) GetUserByEmail(ctx context.Context, email string) (repository.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(repository.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockQuerierMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockQuerier)(nil).GetUserByEmail), ctx, email)
}

// ListTransfers mocks base method.
func (m *MockQuerier) ListTransfers(ctx context.Context, arg repository.ListTransfersParams) ([]repository.ListTransfersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransfers", ctx, arg)
	ret0, _ := ret[0].([]repository.ListTransfersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransfers indicates an expected call of ListTransfers.
func (mr *MockQuerierMockRecorder) ListTransfers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransfers", reflect.TypeOf((*MockQuerier)(nil).ListTransfers), ctx, arg)
}

// TransferPlayer mocks base method.
func (m *MockQuerier) TransferPlayer(ctx context.Context, arg repository.TransferPlayerParams) (repository.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferPlayer", ctx, arg)
	ret0, _ := ret[0].(repository.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferPlayer indicates an expected call of TransferPlayer.
func (mr *MockQuerierMockRecorder) TransferPlayer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferPlayer", reflect.TypeOf((*MockQuerier)(nil).TransferPlayer), ctx, arg)
}

// UpdatePlayer mocks base method.
func (m *MockQuerier) UpdatePlayer(ctx context.Context, arg repository.UpdatePlayerParams) (repository.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlayer", ctx, arg)
	ret0, _ := ret[0].(repository.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePlayer indicates an expected call of UpdatePlayer.
func (mr *MockQuerierMockRecorder) UpdatePlayer(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlayer", reflect.TypeOf((*MockQuerier)(nil).UpdatePlayer), ctx, arg)
}

// UpdateTeam mocks base method.
func (m *MockQuerier) UpdateTeam(ctx context.Context, arg repository.UpdateTeamParams) (repository.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeam", ctx, arg)
	ret0, _ := ret[0].(repository.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeam indicates an expected call of UpdateTeam.
func (mr *MockQuerierMockRecorder) UpdateTeam(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeam", reflect.TypeOf((*MockQuerier)(nil).UpdateTeam), ctx, arg)
}

// UpdateTeamBudget mocks base method.
func (m *MockQuerier) UpdateTeamBudget(ctx context.Context, arg repository.UpdateTeamBudgetParams) (repository.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeamBudget", ctx, arg)
	ret0, _ := ret[0].(repository.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeamBudget indicates an expected call of UpdateTeamBudget.
func (mr *MockQuerierMockRecorder) UpdateTeamBudget(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeamBudget", reflect.TypeOf((*MockQuerier)(nil).UpdateTeamBudget), ctx, arg)
}
